name: Java CI - Build and Test

on:
  pull_request:
    branches:
      - 'main'
      - 'develop' 

  workflow_dispatch: 


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin' 

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Tests
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/testdb
          DB_USERNAME: testuser
          DB_PASSWORD: testpassword

          APPLICATION_JWT_SECRET_KEY: ${{ secrets.APPLICATION_JWT_SECRET_KEY }}
          STRIPE_API_SECRET_KEY: ${{ secrets.STRIPE_API_SECRET_KEY }}
          STRIPE_API_PRICE_ID: ${{ secrets.STRIPE_API_PRICE_ID }}
          STRIPE_API_WEBHOOK_SECRET: ${{ secrets.STRIPE_API_WEBHOOK_SECRET }}
          SPRING_MAIL_USERNAME: ${{ secrets.SPRING_MAIL_USERNAME }}
          SPRING_MAIL_PASSWORD: ${{ secrets.SPRING_MAIL_PASSWORD }}
          FRONTEND_BASE_URL: http://localhost:3000

        run: ./mvnw test

